let suggestions = [
    "iPhone",
    "MacBook",
    "iPad",
    "Apple Watch",
    "AirPods",
    "iOS",
    "macOS",
    "Apple TV",
    "iMac",
    "Mac mini",
    "Apple Music",
    "Apple Podcasts",
    "Apple Fitness+",
    "App Store",
    "Apple Developer",
    "Swift Programming",
    "Xcode",
    "Creating iOS Apps",
    "macOS Development",
    "Apple Design Guidelines",
    "Apple Pencil",
    "Procreate on iPad",
    "Using Final Cut Pro",
    "Logic Pro X",
    "Apple ID",
    "iCloud",
    "AppleCare",
    "Apple Keynote",
    "Apple Events",
    "Apple News",
    "Apple Support",
  ];
  